### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by dylangeofs** [geofs-plugins/plugin-manager-V2#16]
How do you us this? Instructions are not clear enough, and I was really wondering how you use this! Thanks!

**Comment by ron-popov** [comment]
This project is currently in a halt and I don't plan to continue developing it. 
In addition this is not supposed to be used by non developers.

**Comment by yotam180** [comment]
@ron-popov Dylan is a developer. Well, I guess I can call him that. But Ron's right here, we don't use this repository anymore

**Comment by dylangeofs** [comment]
Oh ooops! I forgot to delete this. Yotam uploads my aircrafts for me now so I dont need it. Sorry @ron-popov.
