### ISSUE TITLE
Is it broken intentionally? 

### ISSUE THREAD

**Issue by GarudaKLM001** [geofs-plugins/plugin-manager-V2#18]
Hi, I really love this plugin and I used it a lot. And I know you guys discontinued this plugin. Somebody tried to remake the plugin but it doesn't work. But why doesn't this one work as well? I'm getting "Incorrect aircraft JSON file" errors, which are syntax errors. Did you guys break the plugin on purpose? Or did you guys mess it up on an attempt to update it? Because I can't image the code to just break itself.

**Comment by ron-popov** [comment]
No, we didn't break it on purpose

**Comment by yotam180** [comment]
Don't look at us, it's the CIA
