### ISSUE TITLE
Local Storage key naming

### ISSUE THREAD

**Issue by ron-popov** [geofs-plugins/plugin-manager-V2#3]
I think that when we are saving the content of a certain file should be the name of the file.  
For example when downloading the core file of SkyX we should save it like so ``` localStorage.setItem("core.user.js", fileContent); ```

We could add a prefix to the key string to differentiate it from other local storage values and show that this localStorage value belongs to SkyX, for example ``` SkyX/core.user.js```

**Comment by yotam180** [comment]
Awesome. 👍

**Comment by ron-popov** [comment]
Good, cause i already changed it in base.user.js

**Comment by yotam180** [comment]
Umm. I don't see any change in base.user.js...

**Comment by ron-popov** [comment]
I did those changes in your branch
